name: Build project

on: [push]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    - Android

        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            with:
                fetch-depth: 0

    build:
        needs: Test
        name: Build for ${{ matrix.targetPlatform }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    - Android

        steps:               
          - name: Build
            uses: game-ci/unity-builder@v2
            env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            with:
                targetPlatform: ${{ matrix.targetPlatform }}

          - name: Upload builded file
            uses: actions/upload-artifact@v2
            with:
                name: Build-${{ matrix.targetPlatform }}
                path: build/${{ matrix.targetPlatform }}